### ISSUE TITLE
如下面图，当asideWidth动态变化时，border11的宽度无法动态变化

### ISSUE THREAD

**Issue by zhuangYuFeiHelloGit** [vaemusic/datav-vue3#11]
![image](https://user-images.githubusercontent.com/17961466/185020748-58a730f0-c331-4a5a-8d7b-c3c27d721920.png)

**Comment by vaemusic** [comment]
可以在 `asideWidth` 变动时，调用边框组件的 `initWH` 方法试试，文档里有该方法的说明和使用例子。地址：[Border initWH](https://datav-vue3.netlify.app/Guide/BorderTip.html)

**Comment by zhuangYuFeiHelloGit** [comment]
> 可以在 `asideWidth` 变动时，调用边框组件的 `initWH` 方法试试，文档里有该方法的说明和使用例子。地址：[Border initWH](https://datav-vue3.netlify.app/Guide/BorderTip.html)

感谢回复，我查看了这个链接。请问如何在ts中导入 border的类型。我现在ts的校验认为 `const dvBorder = ref(null);  ` `dvBorder .value` 的类型为 never，无法找到 initWH方法

**Comment by zhuangYuFeiHelloGit** [comment]
> 可以在 `asideWidth` 变动时，调用边框组件的 `initWH` 方法试试，文档里有该方法的说明和使用例子。地址：[Border initWH](https://datav-vue3.netlify.app/Guide/BorderTip.html)

我通过 `const dvBorder = ref<any>(null);` 的方式调用了 `initWH()` ，边框的问题已经解决了。
如果可以的话我还是想导入 `dv-border-box-11` 的类型

**Comment by zhuangYuFeiHelloGit** [comment]
@vaemusic  好的谢谢

**Comment by vaemusic** [comment]
> > 可以在 `asideWidth` 变动时，调用边框组件的 `initWH` 方法试试，文档里有该方法的说明和使用例子。地址：[Border initWH](https://datav-vue3.netlify.app/Guide/BorderTip.html)
> 
> 我通过 `const dvBorder = ref<any>(null);` 的方式调用了 `initWH()` ，边框的问题已经解决了。 如果可以的话我还是想导入 `dv-border-box-11` 的类型

在最新版本 1.3.2 中，用 tsx 重写了边框组件，已经解决该问题。

可以使用下面代码获取边框组件的类型
```js
import { BorderBox11 } from '@kjgl77/datav-vue3'

const dvBorder11 = ref<InstanceType<typeof BorderBox11> | null>(null)
dvBorder11.value?.initWH()
```

边框组件的引入，也推荐使用这种方法以获得更好的 TS 支持
