### ISSUE TITLE
请教，我的项目是vue3 + vite 在使用datav的<dv-decoration-9>无法适配的问题

### ISSUE THREAD

**Issue by HYT810** [vaemusic/datav-vue3#13]
![1](https://user-images.githubusercontent.com/37981766/188098066-52919465-c023-4031-8204-35dcee64afcb.png)
![2](https://user-images.githubusercontent.com/37981766/188098091-f9efa3ed-877b-44b4-bed5-3c57788edc11.png)
修改<dv-decoration-9>标签的宽高，内部svg无法自动缩放。控制台有报错：
Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.

**Comment by vaemusic** [comment]
代码上因为ts有点问题，我等下改下发个新版……

**Comment by vaemusic** [comment]
可以了，更新到 1.2.2 版本试一下

**Comment by HYT810** [comment]
试过了可以了，大佬这个处理速度爆赞！！！
