### ISSUE TITLE
滚动表 行内块级元素 height =0 仍然显示

### ISSUE THREAD

**Issue by zepingwong** [vaemusic/datav-vue3#15]
滚动表，行内使用 p、span 标签时，.ceil高度为零仍然会显示刚刚滚动过去的一行，可以设置 .ceil {overflow: hidden}

**Comment by vaemusic** [comment]
![QQ图片20220906153449](https://user-images.githubusercontent.com/34475515/188574574-a296b25c-225f-4ff7-9b5c-230518e02a93.png)
是data数据里的span高度为0的时候吗

**Comment by zepingwong** [comment]
> ![QQ图片20220906153449](https://user-images.githubusercontent.com/34475515/188574574-a296b25c-225f-4ff7-9b5c-230518e02a93.png) 是data数据里的span高度为0的时候吗

是的，如果这里的span设置了fontsize、lineheight 就会出现上一次滚动数据不完全消失

**Comment by vaemusic** [comment]
有什么可以复现的例子，截图，或者录屏之类的吗
