### ISSUE TITLE
BorderBox11 占用 CPU比较高？

### ISSUE THREAD

**Issue by sertceps** [vaemusic/datav-vue3#17]
作者你好。

单纯的放上边框，没有加东西，浏览器 CPU 占用在 10% 左右波动。
注释掉 Border11 或者换用其它 Border 之后降回 1% 左右。

 `"vue": "^3.2.13"`
`"@liveqing/liveplayer-v3": "^3.1.9"`
操作系统：`win11`
处理器：`i5-1135G7` 四核心八线程
浏览器：`105.0.1343.53` （edge）和 `104.0.5112.102`（chrome）。
```vue
<BorderBox11 title="统计" :color="defaultColor">
  <div class="chart-box">
         //
  </div>
</BorderBox11>
```

**Comment by vaemusic** [comment]
目前分析是svg的动画问题

**Comment by sertceps** [comment]
@vaemusic 
好的，谢谢作者🫡。先用没有动画的 border 了。
