### ISSUE TITLE
nuxt怎么使用，官方的datav是没办法用。出错。

### ISSUE THREAD

**Issue by bbhxwl** [vaemusic/datav-vue3#18]
nuxt怎么使用，官方的datav是没办法用。出错。

**Comment by vaemusic** [comment]
没测试过nuxt

**Comment by bbhxwl** [comment]
> 没测试过nuxt

不太懂原理,出的错误,大佬也许一看就知道吧.
![image](https://user-images.githubusercontent.com/26525599/195488517-68ead1d4-8388-4427-a235-366e625309d5.png)

**Comment by vaemusic** [comment]
> > 没测试过nuxt
> 
> 不太懂原理,出的错误,大佬也许一看就知道吧. ![image](https://user-images.githubusercontent.com/26525599/195488517-68ead1d4-8388-4427-a235-366e625309d5.png)

不是很懂，没怎么用过Nuxt

**Comment by decba78b** [comment]
首先，这个库是vue3的，你的nuxt又是vue2的，vue版本都对不上
