### ISSUE TITLE
计算出来的高度不对

### ISSUE THREAD

**Issue by wfxt0911** [vaemusic/datav-vue3#19]
![image](https://user-images.githubusercontent.com/84564199/197390934-5d5f039e-8f6a-4156-bc79-78308aa3f617.png)
![image](https://user-images.githubusercontent.com/84564199/197390959-11225a62-ae1f-47ee-9ebe-c2e33b575f07.png)
上面2个图的高度对不上 计算出来的高度多了 导致元素展示不完整

**Comment by vaemusic** [comment]
F11全屏试试

**Comment by wfxt0911** [comment]
>F11全屏是没有问题的 有没有办法在不是F11全屏的时候 展示也是完整的呢

**Comment by wfxt0911** [comment]
> > F11全屏是没有问题的 有没有办法在不是F11全屏的时候 展示也是完整的呢



> F11全屏试试

 F11全屏是没有问题的 有没有办法在不是F11全屏的时候 展示也是完整的呢

**Comment by wfxt0911** [comment]
> F11全屏试试

 F11全屏是没有问题的 有没有办法在不是F11全屏的时候 展示也是完整的呢

**Comment by vaemusic** [comment]
> > F11全屏试试
> 
> F11全屏是没有问题的 有没有办法在不是F11全屏的时候 展示也是完整的呢

这个组件设计的就是F11全屏的时候才会完全显示。

不全屏完全显示的话可以参考下 https://gitee.com/MTrun/vue-big-screen-plugin 这个项目
主要适应方案在 `src/utils/useDraw.ts` 文件里

**Comment by wfxt0911** [comment]
> > > F11全屏试试
> > 
> > 
> > F11全屏是没有问题的 有没有办法在不是F11全屏的时候 展示也是完整的呢
> 
> 这个组件设计的就是F11全屏的时候才会完全显示。
> 
> 不全屏完全显示的话可以参考下 https://gitee.com/MTrun/vue-big-screen-plugin 这个项目 主要适应方案在 `src/utils/useDraw.ts` 文件里

非常感谢 立马学习
