### ISSUE TITLE
想请教一下大佬，vue3通过接口获取到数据后，设置进config为什么无效？

### ISSUE THREAD

**Issue by weijianpeng18421** [vaemusic/datav-vue3#21]
想请教一下大佬，vue3通过接口获取到数据后，设置进config为什么无效？
数据有，但就是不显示。
![image](https://user-images.githubusercontent.com/29622256/208033373-3f8f7f18-741e-4784-9ad0-499243a20f99.png)

**Comment by vaemusic** [comment]
建议了解下 Vue 的响应式基础
