### ISSUE TITLE
请教一个dv-conical-column-chart初始值问题

### ISSUE THREAD

**Issue by aierong** [vaemusic/datav-vue3#22]
<dv-conical-column-chart :config="config"
                                         style="width:100%;height:250px;"/>

const config = reactive( {
    data : [
        {
            name : '信阳' ,
            value : 0 ,
        } ,
        {
            name : '漯河' ,
            value : 0 ,
        } ,
    ] ,
    //showValue	显示数值
    showValue : true ,
    //textColor	文字颜色
    textColor : '#1258e3'
} )

dv-conical-column-chart的data中初始值value等于0，页面打开时，浏览器的控制台会报错误：Error: <text> attribute y: Expected length, `"NaN".`

**Comment by aierong** [comment]
同样情况，我按钮单击时，value等于0，也会报错


`
function click1 () {
    // console.log( 'dj' )

    config.data = [
        {
            name : '周口' ,
            value : 0 ,
        } ,
        {
            name : '南阳' ,
            value : 0 ,
        } ,
        {
            name : '漯河' ,
            value : 0 ,
        } ,
    ]
}`

**Comment by vaemusic** [comment]
原本的datav也有这个问题，我找找问题改一下

**Comment by vaemusic** [comment]
已经在 1.4.0 版本中更新了。

**Comment by aierong** [comment]
大佬，这么快解决！赞

我去安装新版本试试看
