### ISSUE TITLE
请教dv-capsule-chart文字颜色问题

### ISSUE THREAD

**Issue by aierong** [vaemusic/datav-vue3#23]
dv-capsule-chart的文字是白色的,如果我的背景也是白色,那就无法看清楚文字

可否像dv-conical-column-chart有一个textColor 可以配置 文字颜色

**Comment by vaemusic** [comment]
已经在 1.4.0 版本中更新添加了。

**Comment by aierong** [comment]
感谢大佬，我去试试看
