### ISSUE TITLE
请教dv-capsule-chart数据源为空问题

### ISSUE THREAD

**Issue by aierong** [vaemusic/datav-vue3#24]
<dv-capsule-chart :config="config"
                              style="width:100%;height:15rem"/>

const config = reactive( {
    data : [
        {
            name : '南阳' ,
            value : 167
        } ,
        {
            name : '周口' ,
            value : 123
        } ,
        {
            name : '漯河' ,
            value : 98
        } ,

    ] ,
    showValue : true ,
    unit : '万元'
} )

function click1 () {
    config.data = [];
}

我单击赋值空数组，好像页面无反应

**Comment by vaemusic** [comment]
已经在 1.4.0 版本中更新了。

**Comment by aierong** [comment]
牛逼，大佬，这么快解决！赞
