### ISSUE TITLE
请教一个dv-scroll-ranking-board文字颜色问题

### ISSUE THREAD

**Issue by aierong** [vaemusic/datav-vue3#27]
大佬，dv-scroll-ranking-board的文字好像默认是白色的，我的程序背景也是白色的，所以看不清文字了，能否增加一个配置文字颜色的属性?  谢谢！

 

textColor | 文字颜色

**Comment by vaemusic** [comment]
可以的，你看看还有其他组件有这样的需求吗，我一次加完好了，总发版也不太好

**Comment by aierong** [comment]
那行，我再去看看
我是东莞，刚刚开始给工厂做大屏，几个主要的组件我都有用了，挺好的，简单方便，谢谢！

**Comment by aierong** [comment]
我就是用你提供的模版，下载回来改的https://github.com/vaemusic/electronic-file

css布局，我一点不会
后端我用.net core写，vue会一些，调用axios取服务端数据
