### ISSUE TITLE
装饰12在动态修改第一个颜色时不生效

### ISSUE THREAD

**Issue by sensiki** [vaemusic/datav-vue3#3]
装饰12在动态修改第一个颜色时不生效，刷新后才生效。其它装饰无此问题

**Comment by vaemusic** [comment]
检查了一下代码，是因为在监听**props.color**的时候，没有重新执行计算路径颜色方法(**calcPathColor**)导致，已经在最新1.1.2修复了，你更新一下试试

**Comment by sensiki** [comment]
给你点赞
