### ISSUE TITLE
大佬，请教dv-conical-column-chart的2个问题

### ISSUE THREAD

**Issue by aierong** [vaemusic/datav-vue3#30]
大佬，我在使用dv-conical-column-chart组件时，遇到2个问题，看看您能否解决

1.这个组件中每根柱是自动排序的，值最高的排第1，但是我们这里大家习惯按循序看，不愿意排序好的
  例如：我们就喜欢：第1个是S1线，第2个是S2线，第3个是S3线，循序乱了，大家不习惯

2.columnColor | 柱颜色 ，能不能给每根柱单独配置颜色

当然，我们提的要求可能不合理，或者您不方便实现，那就算了，再次谢谢您开源提供这套组件

**Comment by vaemusic** [comment]
第一条没问题，配置会像 排名轮播表 一样加 ``sort`` 属性，默认 true ，设置为 false 后不排序

第二条要再考虑考虑看看

**Comment by vaemusic** [comment]
更新了 1.4.2 版本，锥形柱图增加了``sort``，排名轮播表增加了``textColor`` ``color`` ``fontSize``

**Comment by aierong** [comment]
再次感谢

我看到文档也更新了，你的速度很赞

文档部分能否提个小建议：
例如：dv-conical-column-chart 组件增加了新属性：sort  ，有些开发者用的老版本的话，配置这个属性是不起作用的，但是他并不知道是新增加的属性，我的意思是：能否在旁边增加一个说明，告诉开发者是1.4.2 版本才有属性

我自己曾经也碰过几次这样的情况

**Comment by vaemusic** [comment]
好的，确实应该这样
