### ISSUE TITLE
请教dv-water-level-pond文字问题

### ISSUE THREAD

**Issue by aierong** [vaemusic/datav-vue3#31]
dv-water-level-pond组件中的文字是否可以自己配置颜色和大小

谢谢大佬！

const config = reactive( {
    data : [ 66 , 85 , 15 ] ,
    formatter : '{value}个' ,
    colors : [ '#111011' , '#d92ad9' , '#ce0e0e' ]
} )

**Comment by vaemusic** [comment]
水位图这个 colors 属性就可以配置颜色

**Comment by sj7510** [comment]
字体大小可以设置吗
