### ISSUE TITLE
项目插入该插件打包时到rendering chunks (356)...卡了半个小时然后打包成功时怎么回事

### ISSUE THREAD

**Issue by carpZML** [vaemusic/datav-vue3#33]
PLEASE READ: I originally made this template for myself to mocking up apps quicker. I am glad to see you are willing to give it a try! Before your open the issue, please make sure you are reporting bugs in the template itself. **I am NOT creating this template to solve the problems you faced in your project, please use Vue or Vite's discord server to ask questions.** Thank you.

**Describe the bug/issue**

**Comment by vaemusic** [comment]
我目前项目使用没有这个问题，别的也没有反馈这个问题，没法复现，可能是环境，或者配置问题
