### ISSUE TITLE
dv-scroll-ranking-board排名轮播表渲染高度会溢出然后再恢复

### ISSUE THREAD

**Issue by wangrui19970405** [vaemusic/datav-vue3#35]
排名轮播表渲染高度会溢出然后再恢复

溢出：
<img width="461" alt="image" src="https://user-images.githubusercontent.com/49603204/233977295-bd60c797-444d-4b78-9005-a8b50da88c58.png">
恢复：
<img width="336" alt="image" src="https://user-images.githubusercontent.com/49603204/233977334-bd8060e7-1946-4968-9e50-36eaf8ff0d97.png">

**Comment by vaemusic** [comment]
是更新了今天的版本才有的，还是之前版本也有

**Comment by vaemusic** [comment]
更新 `1.4.9` 试试

**Comment by wangrui19970405** [comment]
试过了几个版本 都有

**Comment by vaemusic** [comment]
我这边没见这个问题，方便提供一下最小复现代码吗

**Comment by wangrui19970405** [comment]
<dv-border-box6>
                <div class="box-container">
                  
                  <dv-scroll-ranking-board :config="rank_config" style="width:80%;height:80%;position: relative"/>
                </div>
</dv-border-box6>



<style lang="scss" scoped>

**Comment by vaemusic** [comment]
这段代码还是没能复现问题，或者可以创建一个可以复现问题的 git 仓库

**Comment by wangrui19970405** [comment]
https://github.com/wangrui19970405/datav-issues.git

以上是临时做了一个复现问题的git仓库，请查收

**Comment by vaemusic** [comment]
![datav](https://user-images.githubusercontent.com/34475515/236098405-93453421-2e64-468e-8cdb-3359a95805be.png)

在 77 行的 `el-col` 上把 height 设置为 100% 就可以了

**Comment by wangrui19970405** [comment]
啊 还真的可以，好奇怪，那issues就关闭了，多谢
