### ISSUE TITLE
开发环境运行时错误 

### ISSUE THREAD

**Issue by Jade-beads** [vaemusic/datav-vue3#40]
in ./node_modules/@kjgl77/datav-vue3/dist/datav-vue3.es.js

Module parse failed: Unexpected token (11867:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| function yi(e, t) {
|   var r = typeof e;
>   return t = t ?? md, !!t && (r == "number" || r != "symbol" && yd.test(e)) && e > -1 && e % 1 == 0 && e < t;
| }
| function Ln(e, t, r) {

版本是 1.2.1

运行报错

注释掉这个文件内的 yi这个函数后就可以了

**Comment by vaemusic** [comment]
升级到最新版本试试

**Comment by Jade-beads** [comment]
升级到1.5.0版本后解决
