### ISSUE TITLE
建议翻牌计数器取消     aspect-ratio 属性 

### ISSUE THREAD

**Issue by static7** [vaemusic/datav-vue3#44]
建议翻牌计数器取消    aspect-ratio 属性
![image](https://github.com/vaemusic/datav-vue3/assets/11241063/324c81de-46fd-4df2-824b-606ce54da5b7)
![image](https://github.com/vaemusic/datav-vue3/assets/11241063/31bdf2b9-e406-4402-92b3-c99704de82a4)
如图 造成的间距非常大 很不好调整

**Comment by vaemusic** [comment]
这个组件是用大佬的 [CRender](https://github.com/DataV-Team/CRender) 渲染的
