### ISSUE TITLE
轮播表会影响滚动条

### ISSUE THREAD

**Issue by PL-FE** [vaemusic/datav-vue3#45]
原来的vue2估计也有这个问题。这边找不到原因。怀疑是VUE2复用dom导致的？。
复现代码：[https://codesandbox.io/p/sandbox/determined-blackburn-fxctwg?file=/src/App.vue:15,30](https://gitee.com/link?target=https%3A%2F%2Fcodesandbox.io%2Fp%2Fsandbox%2Fdetermined-blackburn-fxctwg%3Ffile%3D%2Fsrc%2FApp.vue%3A15%2C30)

麻烦大佬帮看看或者告诉下原因(●'◡'●)

**Comment by vaemusic** [comment]
这个组件的实现主要是用定时器来动态控制要显示的元素的高度，每次高度变化是会触发滚动条的。

用的时候需要 ScrollBoard 组件的高度和外层包裹容器的高度一致，来避免这个问题，实际使用当中也应该是高度一致才比较合理。

如果满足不了需求可以研究下 Swiper 里有没有类似相关的轮播组件

**Comment by PL-FE** [comment]
感谢回复，昨天已经找到问题，这个问题其实是浏览器锚点机制。轮播表轮播的设计实现刚好触发这个锚点机制。只要在受影响的滚动条容器加
```js
overflow-anchor: none;
```
<img src="https://user-images.githubusercontent.com/41336612/263511692-4a61df30-270f-42de-b4c2-834af8b700db.gif"/>

## 引用
https://stackoverflow.com/questions/42958463/stop-automatic-scrolling-on-page-content-change
https://stackoverflow.com/a/43001201/16311164
