### ISSUE TITLE
为什么同一个边框的颜色都是一致的？？

### ISSUE THREAD

**Issue by MacJayLee** [vaemusic/datav-vue3#46]
大佬你好 有个问题 

比如我一个页面用了好几个 dv-border-box3 边框  

然后每个边框设置不同的颜色

结果页面所有的dv-border-box3 边框颜色都和最后一个边框一样  全都都一个颜色 好像共用一个全局变量一样

能不能各自有各自的颜色 互不干扰？？

**Comment by MacJayLee** [comment]
大佬能解决一下吗？ 就是颜色属性的问题  其他的bg或者reverse属性都没问题  太奇怪了

**Comment by LeoKun1231** [comment]
一样

**Comment by vaemusic** [comment]
在最新版本 1.7.0 版本中修复了该问题
