### ISSUE TITLE
求更多的demo啊

### ISSUE THREAD

**Issue by LukerSpringtree** [vaemusic/datav-vue3#49]
PLEASE READ: I originally made this template for myself to mocking up apps quicker. I am glad to see you are willing to give it a try! Before your open the issue, please make sure you are reporting bugs in the template itself. **I am NOT creating this template to solve the problems you faced in your project, please use Vue or Vite's discord server to ask questions.** Thank you.

**Describe the bug/issue**
求更多的demo啊

**Comment by vaemusic** [comment]
可以在 gitee 或者 github 上搜搜看看有没有更多的 demo
