### ISSUE TITLE
请问动态环图该怎么不要数字翻牌效果？

### ISSUE THREAD

**Issue by beijibeijing** [vaemusic/datav-vue3#51]
如题~
没找到可配置的地方。

**Comment by vaemusic** [comment]
数字翻拍这块用的原作者的crender实现，具体可以参考crender配置项 http://crender.jiaminghi.com/

**Comment by beijibeijing** [comment]
嗯，不是说数字翻牌本身的设置，而是说动态环图dv-active-ring-chart这里，中间的数字可以有个设置，直接显示数字就好，数字不用翻牌效果

**Comment by vaemusic** [comment]
在最新版本 **1.7.2** 中加入了 `isDigitalFlop` 属性来控制是否使用数字翻牌器来显示数字，另外加了 `numToFixed` 配置来配置数字的小数位数。

**Comment by beijibeijing** [comment]
感谢！！
