### ISSUE TITLE
胶囊柱图CapsuleChart底部labelData可以配置显示的数量么

### ISSUE THREAD

**Issue by beijibeijing** [vaemusic/datav-vue3#52]
如题，胶囊柱图CapsuleChart底部labelData现在默认显示6个数值，如果地方太小，6个数值就挤在一起显示了，能价格配置设置显示的数量么，感谢！

**Comment by vaemusic** [comment]
在最新版本 **1.7.2** 中加入了 `labelNum` 配置来配置显示的数量
