### ISSUE TITLE
请教大佬一个关于dv-button的问题

### ISSUE THREAD

**Issue by RunBoo** [vaemusic/datav-vue3#53]
我通过这样的方式添加了一个按钮：
`<dv-button @click='editParams' border="Border5" style="width: 90px; height: 25px" color="#c8161d" font-color="#e18a3b" fontSize="11">调整相机参数</dv-button>`
效果是整个按钮框比较宽，文字比较小，并且会导致换行，其效果和原因如下图所示：
![image](https://github.com/vaemusic/datav-vue3/assets/28757865/582e49a4-6fe1-4784-86c4-7991133d084a)
![image](https://github.com/vaemusic/datav-vue3/assets/28757865/2002b26c-d691-4d01-913e-814d556f5d00)
如果我能修改这个class='dv-button'要素的padding值，就可以达到想要的效果。
所以想请教一下大佬，在添加按钮的时候，怎样把这样的样式设置参数传递下去，非常感谢！

**Comment by vaemusic** [comment]
可以用
```vue
<style>
:deep(.dv-button){
  // ...
}
</style>
```

**Comment by RunBoo** [comment]
谢谢大佬，但是这样会把其他所有的dv-button全都改掉，有没有方法可以只改想改的这一个按钮？

**Comment by vaemusic** [comment]
那直接在 dv-button 上用style加css样式试试

**Comment by RunBoo** [comment]
`#edit-camera {
  display: flex;
  width: 220px;
  flex-wrap: wrap;
  :deep(.dv-button) {
    padding-left: 10px;
    padding-top: 8px;
    padding-right: 10px;
  }
}`
我尝试了这样，把deep加在按钮类样式属性内部，这样可以了，多谢啦
