### ISSUE TITLE
手机横屏那个全屏容器完全无法兼容，惨不忍睹，另外无法修改svg装饰的线宽度，这导致手机上没法看。

### ISSUE THREAD

**Issue by lozn00** [vaemusic/datav-vue3#54]
PLEASE READ: I originally made this template for myself to mocking up apps quicker. I am glad to see you are willing to give it a try! Before your open the issue, please make sure you are reporting bugs in the template itself. **I am NOT creating this template to solve the problems you faced in your project, please use Vue or Vite's discord server to ask questions.** Thank you.

**Describe the bug/issue**

**Comment by vaemusic** [comment]
我目前用是没什么问题的，主要是得确定好预定的大屏长宽

**Comment by vaemusic** [comment]
等这段时间工作忙完我看看
