### ISSUE TITLE
nuxt3 为什么不能渲染呢？

### ISSUE THREAD

**Issue by bbhxwl** [vaemusic/datav-vue3#55]
![image](https://github.com/vaemusic/datav-vue3/assets/26525599/466cc2d4-e450-4a3d-91a9-a74dfce433ae)
![image](https://github.com/vaemusic/datav-vue3/assets/26525599/9635ea00-d457-4c09-9334-c5ea285ad2f1)
![image](https://github.com/vaemusic/datav-vue3/assets/26525599/9b86d391-eb26-45a8-80fb-aed020943638)

**Comment by vaemusic** [comment]
组件并没有在 nuxt 下测试
