### ISSUE TITLE
pnpm-lock.yaml中部分包的链接已经失效

### ISSUE THREAD

**Issue by NNNNzs** [vaemusic/datav-vue3#56]
<img width="750" alt="image" src="https://github.com/vaemusic/datav-vue3/assets/27205495/77c912d6-0383-424d-9748-68102b3ad452">

<img width="1358" alt="image" src="https://github.com/vaemusic/datav-vue3/assets/27205495/952f5006-5547-481a-8b21-440a6c9c5c24">

原因在于```https://registry.npm.taobao.org```该域名已经停止维护，
建议更新```pnpm-lock.yaml ```或添加到.gitignore

**Comment by vaemusic** [comment]
pnpm-lock文件已更新
