### ISSUE TITLE
胶囊柱图可以增加一个参数控制data的显示数量么

### ISSUE THREAD

**Issue by beijibeijing** [vaemusic/datav-vue3#58]
如题，胶囊柱图的data数量太多时，样式会乱掉。可以加一个像轮播表的rowNum这样的参数来控制每次显示的数量么，然后定时轮换。
感谢！！！

**Comment by beijibeijing** [comment]
再加个控制排序方式的参数，随机动态变化显示或按数值高低排序不变。辛苦！！

**Comment by vaemusic** [comment]
这个需求用 `排名轮播表` 更合适一点
