### ISSUE TITLE
echart 鼠标移入上去没有原生echarts的标注

### ISSUE THREAD

**Issue by jingo-bit** [vaemusic/datav-vue3#6]
PLEASE READ: I originally made this template for myself to mocking up apps quicker. I am glad to see you are willing to give it a try! Before your open the issue, please make sure you are reporting bugs in the template itself. **I am NOT creating this template to solve the problems you faced in your project, please use Vue or Vite's discord server to ask questions.** Thank you.

**Describe the bug/issue**

**Comment by vaemusic** [comment]
项目内的图表 Charts 不是使用的 ECharts，而是使用的原作者写的轻量级图表库，文档地址：http://charts.jiaminghi.com/

复杂项目下，要想获得更好体验建议使用 ECharts
