### ISSUE TITLE
挂载启动报错

### ISSUE THREAD

**Issue by maohongxiang** [vaemusic/datav-vue3#60]
[vite] error while updating dependencies:
Error: ENOENT: no such file or directory, open 'D:\ideaProjects\workspace\layui-vue-admin\node_modules\@jiaminghi\data-view\lib\index.js'

**Comment by vaemusic** [comment]
这是和之前vue2的一起用了吗

**Comment by maohongxiang** [comment]
目前的环境是Vue3 +Vite 4.x，把那个dataV原版包都清干净了，居然还是报错。
我把这两行注释了就不会有问题
[vite] error while updating dependencies: Error: ENOENT: no such file or directory, open 'D:\ideaProjects\workspace\layui-vue-admin\node_modules\@jiaminghi\data-view\lib\index.js'
![image](https://github.com/vaemusic/datav-vue3/assets/148420237/9b172b6a-cd4e-48c0-8b8f-131efbc91c45)
![image](https://github.com/vaemusic/datav-vue3/assets/148420237/6dd41bf5-5865-4c6a-a38f-7433e8f4c873)

**Comment by vaemusic** [comment]
把整个 node_modules 都删了再重新安装一下试试，目前没有复现这个问题的代码
