### ISSUE TITLE
DataV: Failed to get dom node, component rendering may be abnormal!

### ISSUE THREAD

**Issue by gedaaxiba** [vaemusic/datav-vue3#62]
/
![6cb0d1752c4ab968da43dcc7a05c4c9](https://github.com/vaemusic/datav-vue3/assets/103570469/682e6a4a-1a16-45ea-9300-595a5b1aacd3)

![image](https://github.com/vaemusic/datav-vue3/assets/103570469/4a2a4aad-5b62-42cf-8e86-a9d110ef291b)

我已经将页面上的dataV组件包裹echarts全部去除了  剩下的都是没有包裹echarts的dataV组件 是我initWH的时机不对吗

**Comment by vaemusic** [comment]
只有边框组件有initWH方法
