### ISSUE TITLE
平滑折线图出现负数显示bug

### ISSUE THREAD

**Issue by llyyayx** [vaemusic/datav-vue3#8]
在折线图数据为[0,0,10,0,0]，smooth=true，时0-10之间会回显负数，这是charts内部算法问题，您可否解决一下，感谢。
图示：
![问题图示](https://pic1.zhimg.com/v2-ff96c2bf761b22318602f7f08394cb44_b.jpeg)
详细描述：https://www.zhihu.com/question/533645281/answer/2493641854

**Comment by vaemusic** [comment]
组件里的 charts 是用的原作者的轻量级图表库 charts
- 文档地址：http://charts.jiaminghi.com/
- 仓库地址： https://github.com/DataV-Team/Charts

你可以尝试去这个仓库下提 issue 或改用 echarts 试试，不过看情况原作者好像没有空继续维护，建议图表这一块使用 echarts 试试

**Comment by llyyayx** [comment]
> 组件里的 charts 是用的原作者的轻量级图表库 charts
> 
> * 文档地址：http://charts.jiaminghi.com/
> * 仓库地址： https://github.com/DataV-Team/Charts
> 
> 你可以尝试去这个仓库下提 issue 或改用 echarts 试试，不过看情况原作者好像没有空继续维护，建议图表这一块使用 echarts 试试

好的，charts不维护了看样子，强制曲线的话用echar解决吧，感谢您解决了datav在ts框架下的空白
