### ISSUE TITLE
this 的指向错误

### ISSUE THREAD

**Issue by Jade-beads** [vaemusic/datav-vue3#9]
<img width="814" alt="微信截图_20220811112441" src="https://user-images.githubusercontent.com/75240379/184060094-e918e42b-d429-4f8c-9699-9850dfbcfa9d.png">

**Comment by vaemusic** [comment]
该问题在 commit: [(74b2e39)](https://github.com/vaemusic/datav-vue3/commit/74b2e39) 中已经修复过了
